-- Profile photo support.
--
-- Adds `avatar_path` to `public.users` (stores the Storage object path when
-- the user has uploaded a custom photo; null means use OAuth avatar or default).
--
-- Creates a private `avatars` bucket where each user may only read/write their
-- own file at `{user_id}/avatar.jpg`.  Access from the app is via short-lived
-- signed URLs generated by the Supabase client.

-- ── Column ────────────────────────────────────────────────────────────────────

alter table public.users
  add column if not exists avatar_path text;

-- ── Storage bucket ────────────────────────────────────────────────────────────

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  false,                         -- private: no public URLs
  5242880,                       -- 5 MB per file
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do nothing;

-- ── Storage RLS ───────────────────────────────────────────────────────────────
-- File path convention: {user_id}/avatar.jpg
-- (storage.foldername returns an array of path segments; [1] is the first segment)

create policy "avatar: owner select"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "avatar: owner insert"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "avatar: owner update"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "avatar: owner delete"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'avatars'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
